import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { ThemeProvider } from '@/context/theme-provider'
import clsx from 'clsx'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

// fonts
const satoshi = localFont({
    src: './../assets/fonts/Satoshi-Variable.ttf',
    variable: '--font-sans',
})

const polysans = localFont({
    src: './../assets/fonts/PolySans-Slim.otf',
    variable: '--font-heading',
})

export const metadata: Metadata = {
    title: 'Rasul Ismailov | Full-stack Web Developer',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={clsx(
                    'min-h-screen bg-[#000] font-sans',
                    satoshi.variable,
                    polysans.variable,
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Header />

                    {children}

                    <Footer />
                </ThemeProvider>
            </body>
        </html>
    )
}
