import { Toaster } from '@/components/ui/toaster'
import { AppProvider } from '@/context/app-provider'
import { LenisProvider } from '@/context/lenis-provider'
import { ThemeProvider } from '@/context/theme-provider'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'

// fonts
const fontSans = Space_Grotesk({
    subsets: ['latin'],
    variable: '--font-sans',
})

const fontParagraph = localFont({
    src: './../assets/fonts/Aeonik.otf',
    variable: '--font-paragraph',
})

export const metadata: Metadata = {
    title: 'Rasul Ismayil | Full-stack Web Developer',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={clsx(
                    'relative min-h-screen font-sans antialiased selection:text-background selection:bg-foreground dark:selection:bg-accent',
                    fontSans.variable,
                    fontParagraph.variable,
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <LenisProvider>
                        <Toaster />

                        <AppProvider>{children}</AppProvider>
                    </LenisProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
